# Generated by Django 4.1.4 on 2022-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("salary", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F")], max_length=100, null=True
                    ),
                ),
            ],
        ),
    ]
