# Generated by Django 4.1.4 on 2022-12-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
