# Generated by Django 4.1.4 on 2022-12-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
