# Generated by Django 4.1.4 on 2022-12-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_employee_id_alter_staff_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sepal_length", models.FloatField()),
                ("sepal_width", models.FloatField()),
                ("petal_length", models.FloatField()),
                ("petal_width", models.FloatField()),
                ("classification", models.CharField(max_length=30)),
            ],
        ),
    ]
