# Generated by Django 4.1.4 on 2022-12-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_predresults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predresults",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
