# Generated by Django 4.1.4 on 2022-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_predresults_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predresults",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
