# Generated by Django 4.1.4 on 2023-02-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_predresults_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="predresults", name="classification",),
    ]
