# Generated by Django 4.1.4 on 2023-02-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_employeenew"),
    ]

    operations = [
        migrations.DeleteModel(name="EmployeeNew",),
    ]
