# Generated by Django 4.1.4 on 2023-02-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_employeenew"),
    ]

    operations = [
        migrations.AlterModelTable(name="employeenew", table="employee",),
    ]
