# Generated by Django 4.1.4 on 2023-02-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_employeenew_table"),
    ]

    operations = [
        migrations.DeleteModel(name="EmployeeNew",),
    ]
