# Generated by Django 4.1.4 on 2023-02-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_employeedata_delete_book"),
    ]

    operations = [
        migrations.RenameModel(old_name="Employeedata", new_name="EmployeeNew",),
    ]
