# Generated by Django 4.1.4 on 2023-02-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_member"),
    ]

    operations = [
        migrations.DeleteModel(name="EmployeeNew",),
        migrations.DeleteModel(name="Member",),
    ]
